apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Khai báo các thư mục chứa file Manifests (Deployment/Service) gốc của 4 dịch vụ
resources:
- ../../base/auth
- ../../base/product
- ../../base/order
- ../../base/notification

# Đây là nơi GitHub Actions sẽ tự động nhảy vào ghi đè tag sau mỗi lần push code
images:
- name: auth-image-placeholder
  newName: ghcr.io/thang2005hcmus/testcd/auth-service
  newTag: c0edce8358275242ce8967cb137ca0084c5ec14a
- name: notification-image-placeholder
  newName: ghcr.io/thang2005hcmus/testcd/notification-service
  newTag: e751240741b1fc342e0e26b7e59e78ec19ea8a7b
- name: order-image-placeholder
  newName: ghcr.io/thang2005hcmus/testcd/order-service
  newTag: e751240741b1fc342e0e26b7e59e78ec19ea8a7b
- name: product-image-placeholder
  newName: ghcr.io/thang2005hcmus/testcd/product-service
  newTag: e751240741b1fc342e0e26b7e59e78ec19ea8a7b
