apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Khai báo các thư mục chứa file Manifests (Deployment/Service) gốc của 4 dịch vụ
resources:
- ../../base/auth
- ../../base/product
- ../../base/order
- ../../base/notification

# Đây là nơi GitHub Actions sẽ tự động nhảy vào ghi đè tag sau mỗi lần push code
images:
- name: auth-image-placeholder
  newName: ghcr.io/thang2005hcmus/testcd/auth-service
  newTag: adc1ae388b65693d8b5311fd97afe6ca2d6b8747
- name: notification-image-placeholder
  newName: ghcr.io/thang2005hcmus/testcd/notification-service
  newTag: 2779034a40da3f47448e3b6684ceecc282a40d6c
- name: order-image-placeholder
  newName: ghcr.io/thang2005hcmus/testcd/order-service
  newTag: 2779034a40da3f47448e3b6684ceecc282a40d6c
- name: product-image-placeholder
  newName: ghcr.io/thang2005hcmus/testcd/product-service
  newTag: adc1ae388b65693d8b5311fd97afe6ca2d6b8747
