# helm-charts/app-dev/values.yaml
global:
  registry: ghcr.io
services:
  auth-service:
    repository: ghcr.io/thang2005hcmus/testcd/auth-service
    tag: f5b74cff6cfe537c1b7cfeda2eb5bc695577d453
  notification-service:
    repository: ghcr.io/thang2005hcmus/testcd/notification-service
    tag: f5b74cff6cfe537c1b7cfeda2eb5bc695577d453
  order-service:
    repository: ghcr.io/thang2005hcmus/testcd/order-service
    tag: f5b74cff6cfe537c1b7cfeda2eb5bc695577d453
  product-service:
    repository: ghcr.io/thang2005hcmus/testcd/product-service
    tag: f5b74cff6cfe537c1b7cfeda2eb5bc695577d453
