# helm-charts/app-dev/values.yaml
global:
  registry: ghcr.io
services:
  auth-service:
    repository: ghcr.io/thang2005hcmus/testcd/auth-service
    tag: 337872cfbcb365ae17c23a35f0f9310f85922acb
  notification-service:
    repository: ghcr.io/thang2005hcmus/testcd/notification-service
    tag: 337872cfbcb365ae17c23a35f0f9310f85922acb
    env:
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: "kafka-service.testcd.svc.cluster.local:9092" # Sửa 'default' thành namespace bạn triển khai kafka
  order-service:
    repository: ghcr.io/thang2005hcmus/testcd/order-service
    tag: 337872cfbcb365ae17c23a35f0f9310f85922acb
    env:
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: "kafka-service.testcd.svc.cluster.local:9092"
  product-service:
    repository: ghcr.io/thang2005hcmus/testcd/product-service
    tag: 337872cfbcb365ae17c23a35f0f9310f85922acb
